const $=id=>document.getElementById(id),previewOnly=!window.companion;
const api=window.companion||{listen:()=>{},call:async method=>{
 if(method==='init')return {glossary:[],settings:{provider:'gemini',mode:'learn',interval:10,maxCalls:60,geminiModel:'gemini-3.5-flash-lite'},meeting:null};
 throw Error('This is a browser preview. Open MeetingMeaning.exe from Windows File Explorer to use this feature.');
}};
let state={glossary:[],settings:{},meeting:null},capture=null,running=false,starting=false,interims={};
const el=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
const stamp=s=>new Date(Math.max(0,s)*1000).toISOString().slice(11,19);
const name=id=>state.meeting?.names[id]||(id==='you'?'You':id==='remote-unknown'?'Remote speaker':`Speaker ${Number(id.split('-')[1])+1}`);
function error(e){$('error').hidden=false;$('error').textContent=e.message||String(e);}
async function call(method,data){try{return await api.call(method,data);}catch(e){error(e);throw e;}}
function render(){const m=state.meeting;$('count').textContent=state.glossary.length;$('usage').textContent=m?`${m.usage.calls} definition calls · ${m.usage.input.toLocaleString()} input / ${m.usage.output.toLocaleString()} output tokens`:'0 definition calls';
 const started=m?.started?new Date(m.started):null;const validDate=started&&!Number.isNaN(started.getTime());$('meetingDate').hidden=!m;$('meetingDate').textContent=m?(validDate?'Started '+new Intl.DateTimeFormat(undefined,{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(started):'Meeting date unavailable'):'';
 if(m){$('badge').textContent=m.demo?'SAMPLE MEETING':running?'LIVE':'SAVED';$('transcript').replaceChildren();for(const s of [...m.segments].sort((a,b)=>a.time-b.time)){const row=el('div',undefined,'utterance');row.append(el('b',name(s.speaker)),el('time',stamp(s.time)),el('p',s.text));$('transcript').append(row);}if(!m.segments.length)$('transcript').append(el('p','Listening for speech…'));$('transcript').scrollTop=$('transcript').scrollHeight;
 $('speakers').replaceChildren();for(const id of new Set(m.segments.map(s=>s.speaker))){const b=el('button',name(id)+' ✎');b.onclick=()=>{$('speakerId').value=id;$('speakerName').value=name(id);$('renameDialog').showModal();};$('speakers').append(b);}
 $('terms').replaceChildren();for(const t of state.glossary.filter(t=>m.terms.includes(t.id)))$('terms').append(card(t));if(!$('terms').children.length)$('terms').append(el('p',m.demo?'This sample makes no AI calls. Add a glossary entry below to try local definitions.':'Recognized terms will appear here.','hint'));}
 renderLibrary();}
function card(t){const c=el('div',undefined,'card'),b=el('button','Edit');b.onclick=()=>{edit(t);if(!$('libraryDialog').open)$('libraryDialog').showModal();};c.append(b,el('h3',t.term),el('p',t.definition),el('small',t.reviewed?'Reviewed · saved locally':'AI / unreviewed · saved locally'));return c;}
function renderLibrary(){const q=$('search').value.toLowerCase();$('libraryList').replaceChildren();for(const t of state.glossary.filter(t=>(t.term+' '+t.definition).toLowerCase().includes(q)))$('libraryList').append(card(t));}
function edit(t={}){$('termId').value=t.id||'';$('termName').value=t.term||'';$('termDefinition').value=t.definition||'';$('termAliases').value=(t.aliases||[]).join(', ');$('reviewed').checked=!!t.reviewed;$('editHeading').textContent=t.id?'Edit definition':'Add a definition';}
function controls(){$('start').disabled=running||starting;$('stop').disabled=!running;$('demo').disabled=running||starting;$('settings').disabled=running||starting;$('history').disabled=running||starting;}
async function release(){const c=capture;capture=null;if(c){for(const n of c.nodes)n.disconnect();for(const s of c.streams)for(const t of s.getTracks())t.stop();await c.ctx.close();}running=false;interims={};$('interim').textContent='';$('levels').textContent='Mic — / Meeting —';controls();}
async function start(){if(starting||running)return;starting=true;controls();$('error').hidden=true;try{
 if(!state.settings.hasDeepgram)throw Error('Open Settings and add a Deepgram API key before listening.');
 const ctx=new AudioContext({sampleRate:16000});capture={ctx,streams:[],nodes:[]};await ctx.audioWorklet.addModule('capture-worklet.js');
 const mic=await navigator.mediaDevices.getUserMedia({audio:{deviceId:$('mic').value?{exact:$('mic').value}:undefined,echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});capture.streams.push(mic);
 const system=await navigator.mediaDevices.getDisplayMedia({video:true,audio:true});capture.streams.push(system);if(!system.getAudioTracks().length)throw Error('Windows playback audio is unavailable. Check your default playback device.');
 // Keep the required display track alive; it is never read, uploaded or recorded.
 await call('start',{title:$('title').value,rate:ctx.sampleRate});running=true;const levels={mic:0,system:0};let last=0;
 for(const [source,stream]of [['mic',mic],['system',system]]){const input=ctx.createMediaStreamSource(new MediaStream(stream.getAudioTracks()));const node=new AudioWorkletNode(ctx,'pcm');const mute=ctx.createGain();mute.gain.value=0;input.connect(node).connect(mute).connect(ctx.destination);capture.nodes.push(input,node,mute);node.port.onmessage=e=>{if(!running)return;api.audio(source,e.data.bytes);levels[source]=e.data.level;if(Date.now()-last>250){$('levels').textContent=`Mic ${Math.round(levels.mic*100)}% / Meeting ${Math.round(levels.system*100)}%`;last=Date.now();}};for(const track of stream.getAudioTracks())track.onended=()=>{if(running){error('An audio device disconnected. Capture stopped.');stop();}};}
 await ctx.resume();render();
 }catch(e){error(e);await release();await api.call('stop').catch(()=>{});}finally{starting=false;controls();}}
async function stop(){$('stop').disabled=true;await release();await call('stop');render();}
api.listen(({type,data})=>{if(type==='meeting'){state.meeting=data;render();}if(type==='glossary'){state.glossary=data;render();}if(type==='error')error(data);if(type==='definitions-ready')$('error').hidden=true;if(type==='status')$('status').textContent=data;if(type==='capture-stop')release();if(type==='interim'){interims[data.source]=data.text;$('interim').textContent=Object.values(interims).filter(Boolean).join(' · ');}});
$('start').onclick=start;$('stop').onclick=()=>stop().catch(error);$('demo').onclick=()=>call('demo').then(()=>{$('status').textContent='Sample meeting · no audio captured or API calls made';}).catch(()=>{});
$('export').onclick=()=>call('export').catch(()=>{});$('folder').onclick=()=>call('folder').catch(()=>{});$('analyze').onclick=()=>call('analyze').catch(()=>{});
$('library').onclick=()=>$('libraryDialog').showModal();$('search').oninput=renderLibrary;$('clearTerm').onclick=()=>edit();
$('settings').onclick=()=>{for(const id of ['interval','maxCalls','mode','provider','geminiModel'])$(id).value=state.settings[id]||(id==='geminiModel'?'gemini-3.5-flash-lite':'');$('serviceStatus').textContent='';for(const [id,flag] of [['deepgram','hasDeepgram'],['gemini','hasGemini'],['openai','hasOpenai']])$(id).placeholder=state.settings[flag]?'Key saved — leave blank to keep it':'No key saved — paste your API key';$('keyStatus').textContent=previewOnly?'Preview only — API keys cannot be saved here. Open MeetingMeaning.exe from Windows File Explorer, then select Settings in its desktop window.':`Deepgram: ${state.settings.hasDeepgram?'key saved':'not configured'} · OpenAI: ${state.settings.hasOpenai?'key saved':'not configured'} · Gemini: ${state.settings.hasGemini?'key saved':'not configured'}`;$('settingsDialog').showModal();};
$('settingsForm').onsubmit=async e=>{e.preventDefault();try{const data={};for(const id of ['deepgram','openai','gemini','interval','maxCalls','mode','provider','geminiModel'])data[id]=$(id).value;for(const id of ['cleardeepgram','clearopenai','cleargemini'])data[id]=$(id).checked;state.settings=await call('settings',data);$('deepgram').value='';$('openai').value='';$('gemini').value='';$('cleargemini').checked=false;$('cleardeepgram').checked=false;$('clearopenai').checked=false;$('settingsDialog').close();$('error').hidden=true;}catch(e){$('serviceStatus').textContent=e.message;}};
async function serviceAction(action){
 $('refreshModels').disabled=true;$('testDefinitions').disabled=true;$('serviceStatus').textContent='Checking service…';
 try{if(action==='models'){
 const models=await api.call('gemini-models',{gemini:$('gemini').value});if(!models.length)throw Error('No stable Flash-Lite models were listed for this key. Check the project in Google AI Studio.');
 const current=$('geminiModel').value;$('geminiModel').replaceChildren();if(!models.includes(current)){const missing=el('option',current+' (not listed — select another model)');missing.value=current;$('geminiModel').append(missing);}
 for(const model of models){const option=el('option',model);option.value=model;$('geminiModel').append(option);}$('geminiModel').value=current;
 $('serviceStatus').textContent='Available models loaded. Select one, then click Test definitions. Model listing alone does not guarantee generation access.';
 }else{const result=await api.call('test-definitions',{provider:$('provider').value,geminiModel:$('geminiModel').value,key:$($('provider').value).value});$('serviceStatus').textContent='Connected to '+result.model+'. '+result.terms[0].term+': '+result.terms[0].definition+' Save settings to use this selection.';}
 }catch(e){$('serviceStatus').textContent=e.message||String(e);}finally{$('refreshModels').disabled=previewOnly;$('testDefinitions').disabled=previewOnly;}
}
$('refreshModels').onclick=()=>serviceAction('models');$('testDefinitions').onclick=()=>serviceAction('test');
$('termForm').onsubmit=async e=>{e.preventDefault();try{await call('glossary-save',{id:$('termId').value,term:$('termName').value,definition:$('termDefinition').value,aliases:$('termAliases').value,reviewed:$('reviewed').checked});edit();}catch{}};
$('renameForm').onsubmit=async e=>{e.preventDefault();try{await call('rename',{id:$('speakerId').value,name:$('speakerName').value});$('renameDialog').close();}catch{}};
$('history').onclick=async()=>{try{const meetings=await call('history');$('historyList').replaceChildren();for(const m of meetings){const b=el('button',m.title,'historyItem');b.append(el('small',new Date(m.started).toLocaleString()));b.onclick=async()=>{await call('load',{id:m.id});$('historyDialog').close();$('status').textContent='Saved meeting';};$('historyList').append(b);}if(!meetings.length)$('historyList').append(el('p','Your saved meetings will appear here.'));$('historyDialog').showModal();}catch{}};
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
if(previewOnly){$('status').textContent='Browser preview · desktop features unavailable';error('You are viewing the page inside Codex or a browser. Open MeetingMeaning.exe from Windows File Explorer for API-key settings, saved meetings and audio capture.');$('settingsForm').querySelectorAll('input,select,button:not([data-close])').forEach(e=>e.disabled=true);}
call('init').then(async s=>{state=s;render();const devices=await navigator.mediaDevices.enumerateDevices();for(const d of devices.filter(d=>d.kind==='audioinput'&&d.deviceId!=='default')){const o=el('option',d.label||'Microphone');o.value=d.deviceId;$('mic').append(o);}}).catch(error);
